import { useState } from 'react'
import { SeoHead } from '../lib/SeoHead.jsx'
import Reveal from '../components/story/Reveal.jsx'
import { generateOpportunityMap } from '../lib/mapperMock.js'
import GovernanceBadge from '../components/ui/GovernanceBadge.jsx'
import { Copy, Check } from 'lucide-react'

const INDUSTRIES = ['Insurance', 'Financial Services', 'Healthcare', 'SaaS / Software', 'Retail / E-commerce', 'Manufacturing', 'Government / Public Sector', 'Professional Services', 'Other']
const PAINS = ['Manual data processing', 'Repetitive customer support', 'Slow reporting & analytics', 'Complex document review', 'Fragmented internal knowledge', 'Compliance & risk management', 'Other']
const TARGETS = [
    { id: 'cost', label: 'Cost reduction' },
    { id: 'time', label: 'Time savings' },
    { id: 'revenue', label: 'Revenue growth' },
    { id: 'quality', label: 'Quality improvement' },
]
const CONSTRAINTS = ['Cloud', 'On-premises', 'Hybrid', 'No preference']
const TIMELINES = ['< 3 months', '3–6 months', '6–12 months', '12+ months']

const INITIAL_FORM = {
    industry: '',
    pain: '',
    dataReadiness: 'medium',
    riskSensitivity: 'medium',
    targetOutcomes: [],
    deploymentConstraint: '',
    timeline: '',
}

function SegmentedControl({ options, value, onChange, label }) {
    return (
        <div role="group" aria-label={label} className="flex gap-2">
            {options.map((o) => (
                <button
                    key={o.value || o}
                    type="button"
                    onClick={() => onChange(o.value || o)}
                    aria-pressed={value === (o.value || o)}
                    className={`flex-1 py-2 text-xs font-medium rounded-lg border transition-colors ${value === (o.value || o)
                            ? 'bg-pulse-500 border-pulse-500 text-white'
                            : 'border-ink-950/15 text-ink-950/60 hover:border-ink-950/30'
                        }`}
                >
                    {o.label || o}
                </button>
            ))}
        </div>
    )
}

function FormField({ label, id, error, children }) {
    return (
        <div>
            <label htmlFor={id} className="block text-sm font-medium text-ink-950/70 mb-2">{label}</label>
            {children}
            {error && <p role="alert" className="mt-1 text-xs text-red-500">{error}</p>}
        </div>
    )
}

function Output({ result, formData }) {
    const [copied, setCopied] = useState(false)

    const copyBrief = () => {
        const text = [
            `OPPORTUNITY MAP — Generated by bonInfer AI (draft)`,
            `Industry: ${formData.industry} | Pain: ${formData.pain}`,
            '',
            'FAST WINS:',
            ...result.fastWins.map((w, i) => `${i + 1}. ${w.title}: ${w.description}`),
            '',
            'PLATFORM PLAYS:',
            ...result.platformPlays.map((p) => `• ${p.title}: ${p.description}`),
            '',
            'GOVERNANCE CHECKS:',
            ...result.governanceChecks.map((g) => `- ${g}`),
            '',
            'ROI ASSUMPTIONS (target):',
            ...result.roiAssumptions.map((r) => `${r.label}: ${r.value}`),
        ].join('\n')
        navigator.clipboard.writeText(text).then(() => {
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        })
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <GovernanceBadge variant="ai-assisted" label="✦ AI-generated (draft) — review before use" />
                <button
                    onClick={copyBrief}
                    className="flex items-center gap-2 text-xs font-medium text-ink-950/60 hover:text-ink-950 transition-colors border border-ink-950/15 rounded-lg px-3 py-1.5"
                    aria-label="Copy opportunity brief to clipboard"
                >
                    {copied ? <Check size={13} className="text-green-500" /> : <Copy size={13} />}
                    {copied ? 'Copied!' : 'Copy as brief'}
                </button>
            </div>

            <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-950/40 mb-3">Fast wins</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {result.fastWins.map((w) => (
                        <div key={w.title} className="rounded-xl border border-ink-950/8 bg-white/70 p-4 shadow-card">
                            <p className="font-semibold text-ink-950 text-sm mb-1">{w.title}</p>
                            <p className="text-xs text-ink-950/65 leading-relaxed">{w.description}</p>
                            <div className="mt-2 flex flex-wrap gap-1">
                                {w.tags.map((t) => (
                                    <span key={t} className="text-xs bg-sand-200 text-ink-950/55 px-2 py-0.5 rounded-full">{t}</span>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-950/40 mb-3">Platform plays</h3>
                <div className="space-y-3">
                    {result.platformPlays.map((p) => (
                        <div key={p.title} className="rounded-xl border border-ink-950/8 bg-white/60 p-4">
                            <p className="font-semibold text-ink-950 text-sm mb-1">{p.title}</p>
                            <p className="text-xs text-ink-950/65 leading-relaxed">{p.description}</p>
                        </div>
                    ))}
                </div>
            </div>

            <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-950/40 mb-3">Governance checks</h3>
                <ul className="space-y-2">
                    {result.governanceChecks.map((g) => (
                        <li key={g} className="flex items-start gap-2 text-xs text-ink-950/75">
                            <span className="text-amber-600 mt-0.5">▲</span>{g}
                        </li>
                    ))}
                </ul>
            </div>

            <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-950/40 mb-3">ROI assumptions</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    {result.roiAssumptions.map((r) => (
                        <div key={r.label} className="rounded-xl bg-sand-200/50 p-3">
                            <p className="text-lg font-display font-bold text-ink-950">{r.value}</p>
                            <p className="text-xs text-ink-950/55 mt-0.5">{r.label}</p>
                            <GovernanceBadge variant={r.type} className="mt-1.5" />
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}

export default function OpportunityMapper() {
    const [form, setForm] = useState(INITIAL_FORM)
    const [result, setResult] = useState(null)
    const [loading, setLoading] = useState(false)
    const [errors, setErrors] = useState({})

    const set = (field, value) => setForm((f) => ({ ...f, [field]: value }))
    const toggleOutcome = (id) =>
        set('targetOutcomes', form.targetOutcomes.includes(id)
            ? form.targetOutcomes.filter((x) => x !== id)
            : [...form.targetOutcomes, id]
        )

    const validate = () => {
        const e = {}
        if (!form.industry) e.industry = 'Select your industry.'
        if (!form.pain) e.pain = 'Describe your main pain.'
        if (form.targetOutcomes.length === 0) e.targetOutcomes = 'Select at least one outcome.'
        return e
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        const e2 = validate()
        setErrors(e2)
        if (Object.keys(e2).length > 0) return
        setLoading(true)
        setResult(null)
        setTimeout(() => {
            setResult(generateOpportunityMap({ ...form, targetOutcomes: form.targetOutcomes }))
            setLoading(false)
        }, 1200)
    }

    return (
        <>
            <SeoHead
                title="Opportunity Mapper — AI Studio"
                description="Map your AI opportunities in minutes. Our Opportunity Mapper generates fast wins, platform plays, and governance checks based on your context."
                canonical="https://boninfer.com/ai-studio/opportunity-mapper"
            />

            <section className="bg-sand-50 pt-20 pb-12 px-4 sm:px-6 lg:px-8">
                <div className="max-w-3xl mx-auto text-center">
                    <Reveal>
                        <h1 className="font-display text-5xl font-bold text-ink-950 mb-3">Opportunity Mapper</h1>
                    </Reveal>
                    <Reveal delay={100}>
                        <p className="text-lg text-ink-950/65 leading-relaxed">
                            Tell us about your context. We'll map your AI opportunities, platform plays, and governance requirements—in under 2 minutes.
                        </p>
                    </Reveal>
                </div>
            </section>

            <section className="pb-24 px-4 sm:px-6 lg:px-8">
                <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-5 gap-12">
                    {/* Form */}
                    <form onSubmit={handleSubmit} noValidate className="lg:col-span-2 space-y-6" aria-label="Opportunity mapper form">
                        <FormField label="Industry" id="industry" error={errors.industry}>
                            <select
                                id="industry"
                                value={form.industry}
                                onChange={(e) => set('industry', e.target.value)}
                                className="w-full px-3 py-2 rounded-lg border border-ink-950/15 text-sm bg-white text-ink-950 focus:outline-none focus:border-pulse-500"
                            >
                                <option value="">Select industry</option>
                                {INDUSTRIES.map((i) => <option key={i}>{i}</option>)}
                            </select>
                        </FormField>

                        <FormField label="Primary workflow pain" id="pain" error={errors.pain}>
                            <select
                                id="pain"
                                value={form.pain}
                                onChange={(e) => set('pain', e.target.value)}
                                className="w-full px-3 py-2 rounded-lg border border-ink-950/15 text-sm bg-white text-ink-950 focus:outline-none focus:border-pulse-500"
                            >
                                <option value="">Select pain point</option>
                                {PAINS.map((p) => <option key={p}>{p}</option>)}
                            </select>
                        </FormField>

                        <FormField label="Data readiness" id="dataReadiness">
                            <SegmentedControl
                                label="Data readiness"
                                options={[{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }]}
                                value={form.dataReadiness}
                                onChange={(v) => set('dataReadiness', v)}
                            />
                        </FormField>

                        <FormField label="Risk sensitivity" id="riskSensitivity">
                            <SegmentedControl
                                label="Risk sensitivity"
                                options={[{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }]}
                                value={form.riskSensitivity}
                                onChange={(v) => set('riskSensitivity', v)}
                            />
                        </FormField>

                        <div>
                            <p id="outcomes-label" className="text-sm font-medium text-ink-950/70 mb-2">Target outcomes</p>
                            <div role="group" aria-labelledby="outcomes-label" className="grid grid-cols-2 gap-2">
                                {TARGETS.map((t) => (
                                    <button
                                        key={t.id}
                                        type="button"
                                        aria-pressed={form.targetOutcomes.includes(t.id)}
                                        onClick={() => toggleOutcome(t.id)}
                                        className={`py-2 text-xs font-medium rounded-lg border transition-colors ${form.targetOutcomes.includes(t.id)
                                                ? 'border-pulse-500 bg-pulse-500/10 text-pulse-700'
                                                : 'border-ink-950/15 text-ink-950/60 hover:border-ink-950/30'
                                            }`}
                                    >
                                        {t.label}
                                    </button>
                                ))}
                            </div>
                            {errors.targetOutcomes && <p role="alert" className="mt-1 text-xs text-red-500">{errors.targetOutcomes}</p>}
                        </div>

                        <FormField label="Deployment constraint" id="deploymentConstraint">
                            <SegmentedControl
                                label="Deployment constraint"
                                options={['Cloud', 'On-prem', 'Hybrid']}
                                value={form.deploymentConstraint}
                                onChange={(v) => set('deploymentConstraint', v)}
                            />
                        </FormField>

                        <FormField label="Timeline" id="timeline">
                            <select
                                id="timeline"
                                value={form.timeline}
                                onChange={(e) => set('timeline', e.target.value)}
                                className="w-full px-3 py-2 rounded-lg border border-ink-950/15 text-sm bg-white text-ink-950 focus:outline-none focus:border-pulse-500"
                            >
                                <option value="">Select timeline</option>
                                {TIMELINES.map((t) => <option key={t}>{t}</option>)}
                            </select>
                        </FormField>

                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full py-3 bg-pulse-500 text-white font-semibold rounded-xl hover:bg-pulse-600 disabled:opacity-50 transition-colors"
                        >
                            {loading ? 'Generating your map…' : 'Map my opportunities'}
                        </button>
                    </form>

                    {/* Output */}
                    <div className="lg:col-span-3">
                        {loading && (
                            <div className="flex flex-col items-center justify-center py-24 text-ink-950/40" role="status" aria-live="polite">
                                <div className="w-8 h-8 rounded-full border-2 border-pulse-500 border-t-transparent animate-spin mb-3" />
                                <p className="text-sm">Generating your opportunity map…</p>
                            </div>
                        )}
                        {result && !loading && <Output result={result} formData={form} />}
                        {!result && !loading && (
                            <div className="h-full flex items-center justify-center py-24 text-center text-ink-950/30">
                                <div>
                                    <div className="text-4xl mb-3">✦</div>
                                    <p className="text-sm">Fill in the form to generate<br />your opportunity map.</p>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </section>
        </>
    )
}
